### ISSUE TITLE
Import history from other repositories

### ISSUE THREAD

**Issue by chrisburr** [lhcb/starterkit-lessons#2]
If we move multiple current repositories into a single gitbook it would be nice to keep all the existing history. It's possible for a git repo to have multiple initial commits[1] and we could import the other repositories by doing something like (untested):

```bash
git remote add new_repo XXXXX
git fetch
git checkout new_repo/master
git checkout -b add-new-repo
git mv * new_location_for_files
git commit -m "Import new_repo"
# Make a PR as normal
```

[1] https://www.destroyallsoftware.com/blog/2017/the-biggest-and-weirdest-commits-in-linux-kernel-git-history

**Comment by alexpearce** [comment]
It would be _really_ great to keep the history. At the very least, to keep the list of people who have contributed.

So far I've manually converted all the files to GitBook syntax (not much, mostly changing the callouts), but I should make an effort to preserve things more nicely. Doing this now in a nice way will probably mean changing the history of this repo, so it'd be best to do something like this sooner rather than later.

**Comment by alexpearce** [comment]
After some git wrangling 🔨 🔧: [it is done](https://github.com/lhcb/starterkit-lessons/graphs/contributors)!
