### ISSUE TITLE
Ganga, grid usage, etc: Which practices are good and which are bad?

### ISSUE THREAD

**Issue by ryuwd** [lhcb/starterkit-lessons#257]
I've had differing responses to practices I've learned from the Starterkit, from what I've heard in Distributed Analysis, about a couple of things:

### HTCondor usage
corresp. page: https://lhcb.github.io/starterkit-lessons/self-guided-lessons/htcondor.html

Apparently using HTCondor / LXBATCH is against LHCb fair usage policy? See
https://mattermost.web.cern.ch/lhcb/channels/distributed-analysis/s7ckr86kwpyxubu3n6mfsxupia

### Replication of grid files to `CERN-USER` storage elements for analysis purposes
corresp. page: https://lhcb.github.io/starterkit-lessons/second-analysis-steps/managing-files-with-ganga.html
I've been discouraged from doing this, and told I should instead access my files by authenticating with a grid certificate.

**Comment by alexpearce** [comment]
This is a very useful issue! Thanks for bringing these points up, I've also heard them before.

The second point is being addressed in #258. For the first, perhaps the best thing to do is to just have a banner at the top of the page saying that LHCb has no usage quota on the HTCondor system? I suggest that rather than removing the page entirely because it is still useful; folks might not be familiar with the concept of batch systems, and may have access to similar set ups (perhaps also using HTCondor) at their home institutes. This page can still act as guidance for them.

What do you think?

**Comment by ryuwd** [comment]
I agree we shouldn't remove it entirely, this was good documentation for me to read and learn from. I guess the most important thing is people know that a fair usage policy exists, and that the grid job submissions will take it into account for you, while `LXBATCH` won't (and should be avoided)? 
Then people know they should be focusing their efforts on getting familiar with `ganga` and `Dirac` first rather than LXBATCH/HTCondor if they want to be able to submit jobs from lxplus.

**Comment by alexpearce** [comment]
Agreed! Sounds like a great message.

Would you mind opening a PR with that? There is a 'info' block type that we could put this message inside at the top of each page.

**Comment by jpwgnr** [comment]
I guess this can be closed. @chrisburr
