### ISSUE TITLE
IOHelper().inputFiles vs DaVinci().Input

### ISSUE THREAD

**Issue by vlisovsk** [lhcb/starterkit-lessons#28]
In the [Running a minimal DaVinci job locally](https://lhcb.github.io/starterkit-lessons/first-analysis-steps/minimal-dv-job.html) lesson, the proposed way of specifying the input DST is using IOHelper().inputFiles command. At the same time, a lot of people use DaVinci.Input instead.
Is there a deep reason to prefer the IOHelper way of doing things?

**Comment by roelaaij** [comment]
setting `DaVinci().Input` will call `IOHelper(pers, pers).inputFiles`, where `pers`  is the persistency type, which is derived from the `DaVinci().InputType` property. This is basically always `"ROOT"`.

**Comment by alexpearce** [comment]
Indeed, [DaVinci just uses the `IOHelper` behind the scenes](https://gitlab.cern.ch/lhcb/DaVinci/blob/0804be1a3a25407e979063b8ad252863d19a25c3/Phys/DaVinci/python/DaVinci/Configuration.py#L361-372).

Using `IOHelper` in the lessons is nice because it's applicable to other applications (e.g. `LHCbApp`, or `Moore`) which might not have the `Input` property.

**Comment by vlisovsk** [comment]
Agree, it's reasonable.
