### ISSUE TITLE
Bug in setDescriptorTemplate

### ISSUE THREAD

**Issue by joaoabcoelho** [lhcb/starterkit-lessons#65]
I noticed a bug on the setDescriptorTemplate function to automatically add branches for a given decay. Basically, the function assumes the primary decay will always be added as a branch and thus removes the ^ from the first particle in the template. If the user does not specify a branch for the primary decay, this will cause the first branch for secondary particles to not be created. 

Also, for the primary decay, a ^ is still introduced in the addBranches, which is at least not needed, but this does not seem to break anything as far as I could tell.

See lesson here: https://lhcb.github.io/starterkit-lessons/first-analysis-steps/add-tupletools.html

**Comment by chrisburr** [comment]
I can reproduce this with:

```bash
lb-run DaVinci/v44r2 ipython
```

Then run:
```python
from __future__ import print_function
from Configurables import DecayTreeTuple
from DecayTreeTuple.Configuration import *

dtt = DecayTreeTuple()
print(dtt.setDescriptorTemplate('[D*(2010)+ -> ${D0}(D0 -> ${Kminus}K- ${Kplus}K+) ${pisoft}pi+]CC'))
print(dtt.Decay)
print()
dtt = DecayTreeTuple()
print(dtt.setDescriptorTemplate('[${Dstar}D*(2010)+ -> ${D0}(D0 -> ${Kminus}K- ${Kplus}K+) ${pisoft}pi+]CC'))
print(dtt.Decay)
```

The output is, the `D0` is only flagged if the `D*(2010)+` also included:
```
{'pisoft': TupleToolDecay('DecayTreeTuple.pisoft'), 'D0': TupleToolDecay('DecayTreeTuple.D0'), 'Kplus': TupleToolDecay('DecayTreeTuple.Kplus'), 'Kminus': TupleToolDecay('DecayTreeTuple.Kminus')}
[D*(2010)+ -> (D0 -> ^K- ^K+) ^pi+]CC

{'Dstar': TupleToolDecay('DecayTreeTuple.Dstar'), 'pisoft': TupleToolDecay('DecayTreeTuple.pisoft'), 'D0': TupleToolDecay('DecayTreeTuple.D0'), 'Kplus': TupleToolDecay('DecayTreeTuple.Kplus'), 'Kminus': TupleToolDecay('DecayTreeTuple.Kminus')}
[D*(2010)+ -> ^(D0 -> ^K- ^K+) ^pi+]CC
```

**Comment by smaccolini** [comment]
The bug has been fixed in the branch setDescriptorTemplate_Bug_Fix and we are waiting for merging into the master branch [1].
Using

> lb-run  DaVinci/v50r0 ipithon

and running

> dtt = DecayTreeTuple()
print(dtt.setDescriptorTemplate('[D*(2010)+ -> ${D0}(D0 -> ${Kminus}K- ${Kplus}K+) ${pisoft}pi+]CC'))
print(dtt.Decay)
print()
dtt = DecayTreeTuple()
print(dtt.setDescriptorTemplate('[${Dstar}D*(2010)+ -> ${D0}(D0 -> ${Kminus}K- ${Kplus}K+) ${pisoft}pi+]CC'))
print(dtt.Decay)`

One will obtain 

> {'pisoft': TupleToolDecay('DecayTreeTuple.pisoft'), 'D0': TupleToolDecay('DecayTreeTuple.D0'), 'Kplus': TupleToolDecay('DecayTreeTuple.Kplus'), 'Kminus': TupleToolDecay('DecayTreeTuple.Kminus')}
[D*(2010)+ -> ^(D0 -> ^K- ^K+) ^pi+]CC
{'Dstar': TupleToolDecay('DecayTreeTuple.Dstar'), 'pisoft': TupleToolDecay('DecayTreeTuple.pisoft'), 'D0': TupleToolDecay('DecayTreeTuple.D0'), 'Kplus': TupleToolDecay('DecayTreeTuple.Kplus'), 'Kminus': TupleToolDecay('DecayTreeTuple.Kminus')}
[D*(2010)+ -> ^(D0 -> ^K- ^K+) ^pi+]CC

In addition we found another bug in the fact that the '^' it is not deleted for the primary decays if they are more than one (chained with '||'). In fact running

>dtt = DecayTreeTuple()
print(setDescriptorTemplate(dtt,'[${Dstar}D*(2010)+ -> ${D0}(D0 -> ${Kminus}K- ${Kplus}K+) ${pisoft}pi+]CC || [${Ds}D_s+ -> ${Kminus_Ds}K- ${Kplus_Ds}K+ ${pi}pi+]CC'))
print(dtt.Decay)

One obtains

>{'Kplus_Ds': TupleToolDecay('DecayTreeTuple.Kplus_Ds'), 'pisoft': TupleToolDecay('DecayTreeTuple.pisoft'), 'Kplus': TupleToolDecay('DecayTreeTuple.Kplus'), 'Kminus_Ds': TupleToolDecay('DecayTreeTuple.Kminus_Ds'), 'Dstar': TupleToolDecay('DecayTreeTuple.Dstar'), 'pi': TupleToolDecay('DecayTreeTuple.pi'), 'Ds': TupleToolDecay('DecayTreeTuple.Ds'), 'D0': TupleToolDecay('DecayTreeTuple.D0'), 'Kminus': TupleToolDecay('DecayTreeTuple.Kminus')}
[D*(2010)+ -> ^(D0 -> ^K- ^K+) ^pi+]CC || [^D_s+ -> ^K- ^K+ ^pi+]CC

With the fix instead, one will obtain

>{'Kplus_Ds': TupleToolDecay('DecayTreeTuple.Kplus_Ds'), 'pisoft': TupleToolDecay('DecayTreeTuple.pisoft'), 'Kplus': TupleToolDecay('DecayTreeTuple.Kplus'), 'Kminus_Ds': TupleToolDecay('DecayTreeTuple.Kminus_Ds'), 'Dstar': TupleToolDecay('DecayTreeTuple.Dstar'), 'pi': TupleToolDecay('DecayTreeTuple.pi'), 'Ds': TupleToolDecay('DecayTreeTuple.Ds'), 'D0': TupleToolDecay('DecayTreeTuple.D0'), 'Kminus': TupleToolDecay('DecayTreeTuple.Kminus')}
[D*(2010)+ -> ^(D0 -> ^K- ^K+) ^pi+]CC || [D_s+ -> ^K- ^K+ ^pi+]CC
 

[1] = https://gitlab.cern.ch/lhcb/Analysis/merge_requests/348

**Comment by eduardo-rodrigues** [comment]
This MR never made it, unfortunately! Hopefully the new MR https://gitlab.cern.ch/lhcb/Analysis/merge_requests/388 fixes the bug and makes sure the corresponsing test is working again.
